# Generated by Django 3.2.3 on 2021-05-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_patient_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='logo.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, default='p1.jpg', null=True, upload_to=''),
        ),
    ]
